/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beacon from "./Beacon";
export type { beacon };
import type * as diamond from "./Diamond";
export type { diamond };
export type { SecurityToken } from "./SecurityToken";
